services:
  - type: web
    name: rakshak-aayush-backend
    runtime: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BREVO_SENDER_EMAIL
        value: cutegirlxxx038@gmail.com
      - key: BREVO_SENDER_NAME
        value: RAKSHAK-AAYUSH Portal
      - key: DATABASE_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
